services:
  - type: redis
    name: modern-web-app-redis
    ipAllowList: []
    plan: free

  - type: web
    name: modern-web-app-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.20.0
      - key: CI
        value: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: modern-web-app-redis
          envVarKey: REDIS_URL
    healthCheckPath: /api/health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80

  - type: web
    name: modern-web-app-frontend
    env: node
    rootDir: .
    buildCommand: |
      export NODE_VERSION=18.20.0
      echo "Current directory:"
      pwd
      echo "Listing directory contents:"
      ls -la
      echo "Moving to client directory:"
      cd client
      echo "Current directory after cd:"
      pwd
      echo "Listing client directory contents:"
      ls -la
      echo "Installing dependencies:"
      npm install
      echo "Building application:"
      npm run build
    startCommand: cd client && serve -s build
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.20.0
      - key: CI
        value: false
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: modern-web-app-backend
          envVarKey: RENDER_EXTERNAL_URL
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80 