services:
  - type: web
    name: modern-web-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.20.0
    healthCheckPath: /api/health
    autoDeploy: true 