services:
  - type: redis
    name: modern-web-app-redis
    ipAllowList: []
    plan: free

  - type: web
    name: modern-web-app-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: NODE_VERSION
        value: 18.20.0
      - key: CI
        value: false
      - key: PORT
        value: 3001
      - key: REDIS_URL
        fromService:
          type: redis
          name: modern-web-app-redis
          envVarKey: REDIS_URL
    healthCheckPath: /api/health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80

  - type: web
    name: modern-web-app-frontend
    env: node
    rootDir: .
    buildCommand: |
      export NODE_VERSION=18.20.0
      echo "=== Bắt đầu quá trình build ==="
      echo "1. Kiểm tra thư mục hiện tại:"
      pwd
      echo "2. Kiểm tra nội dung thư mục gốc:"
      ls -la
      echo "3. Kiểm tra thư mục client:"
      ls -la client
      echo "4. Di chuyển vào thư mục client:"
      cd client
      echo "5. Kiểm tra lại thư mục hiện tại:"
      pwd
      echo "6. Kiểm tra package.json:"
      if [ -f "package.json" ]; then
        echo "package.json tồn tại"
        cat package.json
      else
        echo "LỖI: Không tìm thấy package.json"
        exit 1
      fi
      echo "7. Cài đặt dependencies:"
      npm install
      echo "8. Build ứng dụng:"
      npm run build
      echo "=== Kết thúc quá trình build ==="
    startCommand: cd client && serve -s build
    envVars:
      - key: NODE_ENV
        value: development
      - key: NODE_VERSION
        value: 18.20.0
      - key: CI
        value: false
      - key: PORT
        value: 3000
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: modern-web-app-backend
          envVarKey: RENDER_EXTERNAL_URL
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80 