services:
  - type: redis
    name: modern-web-app-redis
    ipAllowList: []
    plan: free

  - type: web
    name: modern-web-app-backend
    env: node
    rootDir: server
    buildCommand: |
      echo "=== Kiểm tra môi trường ==="
      echo "Node version:"
      node -v
      echo "NPM version:"
      npm -v
      echo "=== Cài đặt dependencies ==="
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: NODE_VERSION
        value: 18.20.0
      - key: CI
        value: false
      - key: PORT
        value: 3001
      - key: REDIS_URL
        fromService:
          type: redis
          name: modern-web-app-redis
          envVarKey: REDIS_URL
      - key: CORS_ORIGIN
        value: https://modern-web-app-frontend.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80

  - type: web
    name: modern-web-app-frontend
    env: node
    rootDir: client
    buildCommand: |
      echo "=== Bắt đầu quá trình build ==="
      echo "1. Kiểm tra môi trường:"
      echo "Node version:"
      node -v
      echo "NPM version:"
      npm -v
      echo "2. Kiểm tra thư mục hiện tại:"
      pwd
      echo "3. Kiểm tra nội dung thư mục:"
      ls -la
      echo "4. Kiểm tra package.json:"
      if [ -f "package.json" ]; then
        echo "package.json tồn tại"
        cat package.json
      else
        echo "LỖI: Không tìm thấy package.json"
        echo "Tìm kiếm package.json trong toàn bộ dự án:"
        find /opt/render/project/src -name "package.json"
        exit 1
      fi
      echo "5. Cài đặt dependencies:"
      npm install
      echo "6. Build ứng dụng:"
      npm run build
      echo "=== Kết thúc quá trình build ==="
    startCommand: serve -s build
    envVars:
      - key: NODE_ENV
        value: development
      - key: NODE_VERSION
        value: 18.20.0
      - key: CI
        value: false
      - key: PORT
        value: 3000
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: modern-web-app-backend
          envVarKey: RENDER_EXTERNAL_URL
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80 